image: gitpod/workspace-full

ports:
  # Hugo server
  - port: 1313
    onOpen: ignore

tasks:
  - init: >
      brew install hugo &&
      yarn install
github:
  prebuilds:
    branches: false
    pullRequests: true