baseURL = "https://fugu.lol/"
languageCode = "en-us"
title = "Fugu"

[params]
  description = "Fugu is a simple and privacy-friendly product analytics tool that helps you better understand your users."